learning_templates/basicapp/urls.py
from django.urls import path
from basicapp import views

# TEMPLATE TAGGING
# this is what allows Django to use template tagging to map differnet url to basicapp
app_name = 'basicapp'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.urls import include

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls'))
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    # context_dict is what helps us to add template filters
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return  render(request,'basicapp/relative_url_templates.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <!-- This is the base template block that will be used for all the othe URLS -->
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">

    {% block body_block %}
    <!--{# Anything outside of this will be inherited if you use extend.#}-->
    {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h1>This is index.html page showing!</h1>
    <!-- We use | operator to add template filters -->
    <h1>{{ text |cut:'hello' }}</h1>

    <!-- add function is another template filter -->
    <h1>{{ number | add:"99" }}</h1>
    {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER!</h1>
    <h2>This is an example of template inheritance</h2>
    {% endblock %}

learning_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES!</h1>
    <!-- basicapp below refers to app_name = 'basicapp' from the urls.py file -->
    <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
    <p></p>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN PAGE</a>
    <p></p>
    <a href="{% url 'index' %}">LINK TO INDEX PAGE</a>
  </body>
</html>